name: npm-update-package
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  pm-update-package:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12.20.2'
    - run: npm ci
    - run: npx npm-update-package --github-token $GITHUB_TOKEN
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
